import express from "express";
import cors from "cors";
import helmet from "helmet";
import { config } from "./config/env.js";
import healthRoutes from "./routes/healthRoutes.js";
import { notFound } from "./middleware/notFound.js";
import { errorHandler } from "./middleware/errorHandler.js";
const app = express();
app.use(helmet());
app.use(cors({ origin: config.clientOrigin }));
app.use(express.json({ limit: "1mb" }));
app.get("/", (_req, res) => res.json({ name: "MarketLink API", health: "/api/health" }));
app.use("/api/health", healthRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
